---
- name: start scout
  service: name=scout_realtime state=started

- name: restart scout
  service: name=scout_realtime state=restarted

- name: stop scout
  service: name=scout_realtime state=reloaded